INSERT INTO currencies (code, name, symbol)
VALUES ('NGN', 'Nigerian Naira', '₦'),
       ('USD', 'US Dollar', '$'),
       ('EUR', 'Euro', '€'),
       ('GBP', 'British Pound', '£'),
       ('JPY', 'Japanese Yen', '¥'),
       ('CNY', 'Chinese Yuan', '¥'),
       ('INR', 'Indian Rupee', '₹'),
       ('AUD', 'Australian Dollar', '$'),
       ('CAD', 'Canadian Dollar', '$'),
       ('CHF', 'Swiss Franc', 'CHF'),
       ('ZAR', 'South African Rand', 'R'),
       ('KES', 'Kenyan Shilling', 'KSh'),
       ('GHS', 'Ghanaian Cedi', '₵'),
       ('EGP', 'Egyptian Pound', '£'),
       ('BRL', 'Brazilian Real', 'R$'),
       ('MXN', 'Mexican Peso', '$'),
       ('SGD', 'Singapore Dollar', '$'),
       ('HKD', 'Hong Kong Dollar', '$'),
       ('NZD', 'New Zealand Dollar', '$'),
       ('KRW', 'South Korean Won', '₩'),
       ('TRY', 'Turkish Lira', '₺'),
       ('RUB', 'Russian Ruble', '₽'),
       ('SAR', 'Saudi Riyal', '﷼'),
       ('AED', 'UAE Dirham', 'د.إ'),
       ('SEK', 'Swedish Krona', 'kr'),
       ('NOK', 'Norwegian Krone', 'kr'),
       ('DKK', 'Danish Krone', 'kr'),
       ('PLN', 'Polish Zloty', 'zł'),
       ('THB', 'Thai Baht', '฿'),
       ('IDR', 'Indonesian Rupiah', 'Rp'),
       ('MYR', 'Malaysian Ringgit', 'RM'),
       ('PHP', 'Philippine Peso', '₱');
